M48
; DRILL file {KiCad 8.0.6-8.0.6-0~ubuntu24.04.1} date 2024-11-29T10:46:20-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-29T10:46:20-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6-8.0.6-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
%
G90
G05
T1
X7.17Y-3.6
X7.21Y-3.9
X7.25Y-3.6
M30
